package start.module.myvim.options;

import java.util.prefs.BackingStoreException;
import java.util.prefs.Preferences;
import javax.swing.table.DefaultTableModel;
import start.module.myvim.utilities.VIEXPairTable;
import start.module.myvim.utilities.VIEXPairTable.CATEGORY;
import static start.module.myvim.utilities.VIEXOptions.*;

/**
 *
 * @author jker
 */
public class KeyPairPanel extends javax.swing.JPanel {

    /** Creates new form KeyPairPanel */
    public KeyPairPanel() {
        initComponents();
        charsModel = (DefaultTableModel) charsPairTable.getModel();
        templatesModel = (DefaultTableModel) templateTable.getModel();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        charsPairTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        templateTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        charsPairTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "StartKey", "EndKey"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(charsPairTable);
        charsPairTable.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(KeyPairPanel.class, "KeyPairPanel.charsPairTable.columnModel.title0")); // NOI18N
        charsPairTable.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(KeyPairPanel.class, "KeyPairPanel.charsPairTable.columnModel.title1")); // NOI18N

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText(org.openide.util.NbBundle.getMessage(KeyPairPanel.class, "KeyPairPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(KeyPairPanel.class, "KeyPairPanel.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton2.setText(org.openide.util.NbBundle.getMessage(KeyPairPanel.class, "KeyPairPanel.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, java.awt.BorderLayout.PAGE_END);

        templateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Suffix", "Template Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(templateTable);
        templateTable.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(KeyPairPanel.class, "KeyPairPanel.templateTable.columnModel.title0")); // NOI18N
        templateTable.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(KeyPairPanel.class, "KeyPairPanel.templateTable.columnModel.title1")); // NOI18N

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(KeyPairPanel.class, "KeyPairPanel.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        charsModel.addRow(new Object[]{"", ""});
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        templatesModel.addRow(new Object[]{"", ""});
    }//GEN-LAST:event_jButton2ActionPerformed

    void load() {
        loadTablePref(charsPref, charsModel);
        loadTablePref(templatesPref, templatesModel);
    }

    void store() {
        saveTablePref(CATEGORY.CHAR_PAIR, charsPref, charsModel);
        saveTablePref(CATEGORY.TEMPLATE_PAIR, templatesPref, templatesModel);
    }

    private void saveTablePref(CATEGORY cat, Preferences node, DefaultTableModel model) {
        int rows = model.getRowCount();
        VIEXPairTable pair = VIEXPairTable.getInstance();
        for (int i = 0; i < rows; i++) {
            Object name = model.getValueAt(i, 0);
            Object value = model.getValueAt(i, 1);
            if (name != null && ((String)name).length() > 0) {
                String sn = (String)name;
                String sv = (String)value;
                node.put(sn, sv);
                pair.addPair(cat, sn, sv);
            }
        }
    }

    private DefaultTableModel charsModel = null;
    private DefaultTableModel templatesModel = null;
    private Preferences charsPref = getPreference(CHAR_PAIR);
    private Preferences templatesPref = getPreference(FILE_TEMPLATE);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable charsPairTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable templateTable;
    // End of variables declaration//GEN-END:variables

}
